Add progress log option
primenumber-dev/embulk-output-http_json pull request #1
Opened 2022-05-24 16:47 UTC by d-hrs

こんな感じのログがでる。
```
2022-05-24 16:45:57.666 +0000 [INFO] (main): Started Embulk v0.9.26
2022-05-24 16:45:57.781 +0000 [INFO] (0001:transaction): Loaded plugin embulk/output/http_json from a load path
2022-05-24 16:45:57.968 +0000 [INFO] (0001:transaction): Loaded plugin embulk-parser-jsonl (0.2.2)
2022-05-24 16:45:57.995 +0000 [INFO] (0001:transaction): Listing local files at directory '.' filtering filename by prefix '00909'
2022-05-24 16:45:57.997 +0000 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2022-05-24 16:45:58.017 +0000 [INFO] (0001:transaction): Loading files [009096.jsonl, 009097.jsonl, 009099.jsonl, 009098.jsonl]
2022-05-24 16:45:58.066 +0000 [INFO] (0001:transaction): Using local thread executor with max_threads=32 / output tasks 16 = input tasks 4 * 4
2022-05-24 16:45:58.123 +0000 [INFO] (0001:transaction): HV000001: Hibernate Validator 7.0.1.Final
2022-05-24 16:45:58.323 +0000 [INFO] (0001:transaction): {done:  0 / 4, running: 0}
2022-05-24 16:46:04.311 +0000 [INFO] (ProgressLogger): request count: 20, response time avg: 1046 ms
2022-05-24 16:46:09.311 +0000 [INFO] (ProgressLogger): request count: 46, response time avg: 860 ms
2022-05-24 16:46:14.311 +0000 [INFO] (ProgressLogger): request count: 73, response time avg: 823 ms
2022-05-24 16:46:19.311 +0000 [INFO] (ProgressLogger): request count: 99, response time avg: 808 ms
2022-05-24 16:46:24.311 +0000 [INFO] (ProgressLogger): request count: 125, response time avg: 794 ms
2022-05-24 16:46:29.311 +0000 [INFO] (ProgressLogger): request count: 150, response time avg: 800 ms
2022-05-24 16:46:34.311 +0000 [INFO] (ProgressLogger): request count: 175, response time avg: 794 ms
2022-05-24 16:46:39.311 +0000 [INFO] (ProgressLogger): request count: 201, response time avg: 794 ms
2022-05-24 16:46:44.311 +0000 [INFO] (ProgressLogger): request count: 227, response time avg: 793 ms
2022-05-24 16:46:49.311 +0000 [INFO] (ProgressLogger): request count: 254, response time avg: 786 ms
2022-05-24 16:46:52.842 +0000 [INFO] (0001:transaction): {done:  3 / 4, running: 1}
2022-05-24 16:46:52.842 +0000 [INFO] (0001:transaction): {done:  3 / 4, running: 1}
2022-05-24 16:46:52.842 +0000 [INFO] (0001:transaction): {done:  3 / 4, running: 1}
2022-05-24 16:46:53.007 +0000 [INFO] (0001:transaction): {done:  4 / 4, running: 0}
2022-05-24 16:46:53.008 +0000 [INFO] (0001:transaction): request count: 272, response time avg: 779 ms
2022-05-24 16:46:53.009 +0000 [INFO] (0001:transaction): {"responses":[{"status_code":201,"status_code_class":200,"response_body":{"purchases_processed":75,"message":"success"}},{"status_code":201,"status_code_class":200,"response_body":{"purchases_processed":75,"message":"success"}
```

2022-05-24 16:53 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPluginDelegate.java
> +        ProgressLogger.setSchedule(task.getProgressLogOutputIntervalSeconds());
`transaction` で呼び出したかったが、 `RestClientInputPluginBase` で `final` ついているので、 overrideできない。
https://github.com/embulk/embulk-base-restclient/blob/6af1941d999d2f06b0de118e2b4a4e815d6d805c/src/main/java/org/embulk/base/restclient/RestClientInputPluginBase.java#L93-L95

処理差し込めそうなのが、 `validateOutputTask` だけな感じがしたので、ここで呼び出している。
https://github.com/embulk/embulk-base-restclient/blob/6af1941d999d2f06b0de118e2b4a4e815d6d805c/src/main/java/org/embulk/base/restclient/RestClientOutputPluginBaseUnsafe.java#L56-L61

2022-05-24 16:55 UTC, d-hrs commented
問題なさそうならこのp-rはcloseして、trocco-ioのほうにp-r出す

2022-05-25 00:31 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPlugin.java
> +        @Config("progress_log_output_interval_seconds")
もう少し短くしたい。 `logging_interval` くらいでもよさそうかな。ちょっと全体見てみて名前考える。

2022-05-25 00:32 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPluginDelegate.java
> +        ProgressLogger.setSchedule(task.getProgressLogOutputIntervalSeconds());
さすがにココじゃない方が良さそう。適切っぽい場所探す。

2022-05-25 00:37 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +            return;
0 以下ならエラーじゃない？
disabled になる仕様ならログを吐いて retrun してほしい。

2022-05-25 00:41 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPluginDelegate.java
> +        ProgressLogger.setSchedule(task.getProgressLogOutputIntervalSeconds());
ﾃﾞｽﾖﾈｰ。いったいどこなんだろう。ﾜｶﾗﾅｲ。

2022-05-25 01:09 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPluginDelegate.java
> +        ProgressLogger.setSchedule(task.getProgressLogOutputIntervalSeconds());
ココしか無さそうだった。

`configureTask` ってメソッドを作って、`validateOutputTask` の一番最初で呼ぶようにして、 `ProgressLogger.setSchedule` は `configureTask` の中で呼ぶようにしてくれる？

2022-05-25 01:10 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +    public static void setSchedule(long delaySecond) {
set 以外のことをしすぎなので名前を変える。 1度しか呼べないので `initializeLogger` とかで良さそう。
あと `delaySeconds` は インターフェース的には意味分からない変数名なので intervalSecords とかの方が良さそう。

2022-05-25 01:21 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +public class ProgressLogger {
Global ってワードを名前に入れても良いのかもね。変数名で使ってるし。

2022-05-25 01:22 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +public class ProgressLogger {
ちなみに logger は普通に実装して、logger を保持する static 変数をどこかに定義する方がベターです。

2022-05-25 06:36 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +public class ProgressLogger {
> Global ってワードを名前に入れても良いのかもね。変数名で使ってるし。

fixed: a7496d3780699947ec843c491542aabcbe7f6a35

> ちなみに logger は普通に実装して、logger を保持する static 変数をどこかに定義する方がベターです。

fixed: 021f6d7981c4979df5b70141647206956de0bc5e

2022-05-25 06:36 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPluginDelegate.java
> +        ProgressLogger.setSchedule(task.getProgressLogOutputIntervalSeconds());
fixed: 08d834ac8653daaf30981859e8e2fbf3a9586425

2022-05-25 06:37 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPlugin.java
> +        @Config("progress_log_output_interval_seconds")
fixed: 576c4c1

2022-05-25 06:37 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +    public static void setSchedule(long delaySecond) {
fixed: 48bf384

2022-05-25 06:39 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +            return;
fixed: 69be86c

> 0 以下ならエラーじゃない？

アノテーション入れてますが、はじいたほうがいいですか？
https://github.com/primenumber-dev/embulk-output-http_json/blob/a7496d3780699947ec843c491542aabcbe7f6a35/src/main/java/org/embulk/output/http_json/HttpJsonOutputPlugin.java#L121-L124

2022-05-25 06:40 UTC, d-hrs commented
再レビューｵﾈｼｬｽ 🙇

2022-05-25 07:11 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/GlobalProgressLogger.java
> +public class GlobalProgressLogger {
static 変数にインスタンスを積めることになったので Global である必要がなくなった

2022-05-25 07:11 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/GlobalProgressLogger.java
> +    private static AtomicLong globalElapsedTime = new AtomicLong(0);
このへんも not static

2022-05-25 07:11 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/GlobalProgressLogger.java
> +    private static ScheduledExecutorService service;
これも not static

2022-05-25 07:12 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/GlobalProgressLogger.java
> +        if (service != null) {
static 関数ではなくなったので initializeLogger は private 変数にしてコンストラクタで実行してください。
そうすると service とかも final で良くなる。

2022-05-25 07:12 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/util/GlobalProgressLogger.java
> +public class GlobalProgressLogger {
あっ、たしかに

2022-05-25 07:13 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/GlobalProgressLogger.java
> +                service.shutdown();
```suggestion
                service.shutdown();
                service = null;
```

2022-05-25 07:15 UTC, civitaspo requested changes
static な部分や not final な変数を極力減らしてください

2022-05-25 07:47 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/util/GlobalProgressLogger.java
> +                service.shutdown();
finalにしたらnull入れれないですね。
意図としては、finishが複数回呼ばれたとき serviceがnullじゃなかったらoutputProgressが複数回呼ばれちゃう(=ログの重複ある)じゃん。ってことですよね？

2022-05-25 07:54 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/util/GlobalProgressLogger.java
> +                service.shutdown();
ので、このように
https://github.com/primenumber-dev/embulk-output-http_json/blob/a1718285a835b8bf72c62095e3e21e1435ca85d9/src/main/java/org/embulk/output/http_json/util/ProgressLogger.java#L42-L47

(たぶん、意図はあってるはず..)

2022-05-25 07:54 UTC, d-hrs commented
fixed a171828

2022-05-25 13:14 UTC, civitaspo reviewed
あとすこし！

2022-05-25 13:14 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +    private AtomicLong globalElapsedTime = new AtomicLong(0);
final

2022-05-25 13:14 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +            logger.warn("disabled progress log.");
service を constructorで初期化しちゃって disableのケースはnullとか入れたほうが無駄なスレッド切られなくてよさそう。

ちなみに僕は変数たち全部コンストラクタ内で代入しちゃう派閥。コンストラクタはシンプルに受け取ったものをそのまま代入するだけにして、別途オーバーロードするコンストラクタを作ってその中でデフォ値を入れるような実装。テスタビリティ上がるし拡張もしやすくなるのでオススメ。

2022-05-25 13:14 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPlugin.java
> +        @ConfigDefault("0")
`2s` とか `6h` とかで受け取れるとアツい

2022-05-26 01:09 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/GlobalProgressLogger.java
> +                service.shutdown();
あ、たしかに > final

if service = null な条件が合ったから、使うなら null 入れないとじゃんって意図だった。
意図はあってる！

2022-05-26 01:11 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPlugin.java
> +        @ConfigDefault("0")
これは must じゃなくてそういう型がどこかに落ちてたらいいなぁくらいの温度感。
というかこのクラスをまるっと持ってくるのが良いかも。
https://github.com/treasure-data/digdag/blob/42ea7cb71270957ea6424c2df88dd7c65d248789/digdag-plugin-utils/src/main/java/io/digdag/util/Durations.java

2022-05-26 06:04 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +    private AtomicLong globalElapsedTime = new AtomicLong(0);
あぁ、たしかにfinalにできるのか
fixed: a8ef554

2022-05-26 06:06 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +            logger.warn("disabled progress log.");
fixed: 4048730

コンストラクタでservice初期化
無効の場合はserviceはshutdown
finish時のoutputをservice経由で実行(無効時はserviceはshutdown済みなので実行されない)

2022-05-26 06:41 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPlugin.java
> +        @ConfigDefault("0")
fixed: e8bfb93 ffd3051

単に時間を表現するクラス https://docs.oracle.com/javase/jp/8/docs/api/java/time/Duration.html だけど、duration = 持続時間的なイメージがあるので、Duration(持続時間)なの？Interval (間隔)なの？みたいな感じがある

2022-05-26 06:51 UTC, d-hrs commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPlugin.java
> +        @ConfigDefault("0")
あと文字にしたので、 `@PositiveOrZero` のアノテーション消したのでマイナスとかフォーマット変なの入れると、パースエラーになります > `org.embulk.exec.PartialExecutionException: java.time.format.DateTimeParseException: Invalid duration`

https://github.com/primenumber-dev/embulk-output-http_json/blob/e8bfb93b0c5019344905564d02525a8924226c6b/src/main/java/org/embulk/output/http_json/util/Durations.java#L13 をの部分をpublicな定数にして`@Pattern(regex)` に設定すればアノテーションはじけるけど、まぁそこまでしなくても…やります？

2022-05-27 01:23 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/HttpJsonOutputPlugin.java
> +        @ConfigDefault("0")
> やります？

やらない。想定していたのは `Durations` を👇のようなかんじで Embulk が `@Config` で扱えるような型にしてあげるような実装だった。それだと PluginTask の定義時点で String じゃなくDurations で受け取れるので loadConfig する時点で validation エラーを吐ける。

https://github.com/embulk/embulk-output-sftp/blob/71eb637d30b26894153c082c05bbcbc40c90fce2/src/main/java/org/embulk/output/sftp/ProxyTask.java#L56-L100

あんまり本質的では無いところではあるので今の実装(Stirng で受け取って使うときに Durations でエラーが出る状態)でも大丈夫 🙆‍♂️

2022-05-27 01:34 UTC, civitaspo commented on src/main/java/org/embulk/output/http_json/util/ProgressLogger.java
> +    }
こんなイメージ

```suggestion
        public ProgressLogger(ScheduledExecutorService service,  AtomicLong globalRequestCount, AtomicLong globalElapsedTime) {
            this.service = service;
            this.globalRequestCount;
            this.globalElapsedTime = globalElapsedTime;
        }

        public ProgressLogger(Duration loggingInterval) {
            if (loggingInterval.getSeconds() <= 0) {
                this(null, new AtomicLong(0), new AtomicLong(0));
            }
            else {
                this(newScheduledExecutor(loggingInterval), new AtomicLong(0), new AtomicLong(0));
            }
        }
        
        public ScheduledExecutorService newScheduledExecutor(Duration loggingInterval) {
            ScheduledExecutorService service = Executors.newSingleThreadScheduledExecutor(
                        new ThreadFactoryBuilder()
                                .setNameFormat(ProgressLogger.class.getSimpleName())
                                .build());
            service.scheduleAtFixedRate(
                () -> outputProgress(), INITIAL_DELAY_SECONDS, loggingInterval, TimeUnit.SECONDS);
            return service;
        }
```

2022-05-27 01:35 UTC, civitaspo approved these changes
yosage

2022-05-27 02:41 UTC, merged